[steam]
; Application ID (http://store.steampowered.com/app/%appid%/)
appid = 480
; Current game language.
; Uncomment this option to turn it on.
; Default is "english".
language = schinese
; Enable/disable automatic DLC unlock. Default option is set to "false".
; Keep in mind that this option  WON'T work properly if the "[dlc]" section is NOT empty
unlockall = true
; Original Valve's steam_api.dll.
; Default is "steam_api_o.dll".
orgapi = steam_api_o.dll
; Original Valve's steam_api64.dll.
; Default is "steam_api64_o.dll".
orgapi64 = steam_api64_o.dll
; Enable/disable extra protection bypasser.
; Default is "false".
extraprotection = false
; The game will think that you're offline (supported by some games).
; Default is "false".
forceoffline = false
; Some games are checking for the low violence presence.
; Default is "false".
;lowviolence = true
; Purchase timestamp for the DLC (http://www.onlineconversion.com/unix_time.htm).
; Default is "0" (1970/01/01).
;purchasetimestamp = 0

[steam_misc]
; Disables the internal SteamUser interface handler.
; Does have an effect on the games that are using the license check for the DLC/application.
; Default is "false".
disableuserinterface = false

[dlc]
4232030=Nioh 3 - Lone Wolf's Armor
4232020=Nioh 3 - Youngblood Armor
4232000=Nioh 3 - Kusanagi Netsuke Charm
4003940=Nioh 3 - Chijiko Netsuke Charm
4003930=Nioh 3 Season Pass		6 February 2026
4003920=Nioh 3 - Kodama Netsuke Charm
4003910=Nioh 3 - Infernal Weapons Set
4003900=Nioh 3 - Hellfrost Equipment Set (Hellfrost Warrior Armor set + Hellfrost Ninja Attire set)		6 February 2026
4003890=Nioh 3 - Scampuss Furball Netsuke Charm
4003880=Nioh 3 - Hellfire Equipment Set (Hellfire Warrior Armor set + Hellfire Ninja Attire set)