[Main]
RealAppId=3681010
FakeAppId=480
#Language=english
BuildId=0

[Misc]
Overlay=true
UnlockAllDLC=true
ShowOnlyPiratedServers=false

[Interfaces]
Apps=True
User=True
Stats=True
Storage=True
Utils=True
Workshop=False
Inventory=True
Friends=True
[DLC]
4232030=Nioh 3 - Lone Wolf's Armor
4232020=Nioh 3 - Youngblood Armor
4232000=Nioh 3 - Kusanagi Netsuke Charm
4003940=Nioh 3 - Chijiko Netsuke Charm
4003930=Nioh 3 Season Pass		6 February 2026
4003920=Nioh 3 - Kodama Netsuke Charm
4003910=Nioh 3 - Infernal Weapons Set
4003900=Nioh 3 - Hellfrost Equipment Set (Hellfrost Warrior Armor set + Hellfrost Ninja Attire set)		6 February 2026
4003890=Nioh 3 - Scampuss Furball Netsuke Charm
4003880=Nioh 3 - Hellfire Equipment Set (Hellfire Warrior Armor set + Hellfire Ninja Attire set)

[FreeTP]
Id=0