[app::dlcs]
# should the emu report all DLCs as unlocked, default=1
unlock_all=0
1896320=ELDEN RING Adventure Guide
2855520=ELDEN RING Shadow of the Erdtree - Artbook & Soundtrack
2855530=ELDEN RING Shadow of the Erdtree Bonus Gesture
3655690=Unknown Steam app 3655690
1896300=ELDEN RING Digital Artbook & Original Soundtrack
1922350=ELDEN RING - EU Pre-Purchase DLC Bundle
2778580=ELDEN RING Shadow of the Erdtree
1799420=ELDEN RING Bonus Gesture
2778590=ELDEN RING Shadow of the Erdtree Premium Bundle

