[Config]
; Specify the targets which are protected by Denuvo, seperate with commas
Targets=CrimsonDesert.exe

; Automatically load/unload the hypervisor
AutoLoadHV=true

; Show a message box prompting to revert the security feature changes
GoRevertMsg=true

; Enable this if a game has Capcom Anti-Tamper
Capcom=false

[Sections]
; Define the sections for each target where the Denuvo code resides in
; Set this to "auto" to automatically choose the largest executable section
CrimsonDesert.exe=auto

[Patches:CrimsonDesert.exe]
; Add custom patches here (e.g. Steam ID patch)
; Format: <rva_as_hex>=<patch_as_hex_string>
1302A169=48BBBA5600000100100190

[Hashes]
CrimsonDesert.exe=ecfde361e2bb8f4f