[Config]
; Specify the targets which are protected by Denuvo, seperate with commas
Targets=re9.exe

; Automatically load/unload the hypervisor
AutoLoadHV=true

; Show a message box prompting to revert the security feature changes
GoRevertMsg=true

; Enable this if a game has Capcom Anti-Tamper
Capcom=true

[Sections]
; Define the sections for each target where the Denuvo code resides in
; Set this to "auto" to automatically choose the largest executable section
re9.exe=auto

[Patches:re9.exe]
; Add custom patches here (e.g. Steam ID patch)
; Format: <rva_as_hex>=<patch_as_hex_string>
17F61483=48BB9815432E0100100190
16FC56E2=48B89815432E0100100190
53F4B75=B001
53F4B9B=9090
159FAF82=909090
15A00910=909090
15A05785=9090909090909090
15A08804=909090
15A10EDC=4E

[Hashes]
re9.exe=20bdc6a72bf9531a