[app::dlcs]
# should the emu report all DLCs as unlocked, default=1
unlock_all=0
3319490=ELDEN RING NIGHTREIGN Bonus Gesture
3531720=Unknown Steam app 3531720
3515600=ELDEN RING NIGHTREIGN Digital Artbook & Mini Soundtrack
3637850=ELDEN RING NIGHTREIGN CE Content (Retail)
3515610=ELDEN RING NIGHTREIGN - Deluxe Upgrade Pack

