[Config]
; Specify the target which is protected by Denuvo, defaults to game executable
Target=MONSTER_HUNTER_STORIES_3_TWISTED_REFLECTION.exe

; Define the section where the Denuvo code resides in
; Set this to "auto" to automatically choose the largest executable section
Section=auto

; Automatically load/unload the hypervisor, requires watchdog.exe
AutoLoadHV=true

; Show a message box prompting to revert the security feature changes
GoRevertMsg=true

[Patches]
; Add custom patches here (e.g. Steam ID patch)
; Format: <rva_as_hex>=<patch_as_hex_string>
1026EC37=48B8ADB8022E0100100190
E4359F=E9DC030000
E3FACB=C641410190
E3FAD3=9090909090
114A62B5=90909090
114BD347=9090909090909090
114C293F=90909090
114C6388=909090
114CC805=9090909090909090