[app::dlcs]
# 1=report all DLCs as unlocked
# 0=report only the DLCs mentioned
# some games check for "hidden" DLCs, hence this should be set to 1 in that case
# but other games detect emus by querying for a fake/bad DLC, hence this should be set to 0 in that case
# default=1
unlock_all=0
# format: ID=name
3116950=Monster Hunter Wilds - Hunter Layered Armor Set: Guild Knight
3116960=Monster Hunter Wilds - Talisman: Hope Charm
3116990=Monster Hunter Wilds - Gesture Set Vol. 1
3117030=Monster Hunter Wilds - Hunter Layered Armor: Wyverian Ears
3117050=Monster Hunter Wilds - Premium Bonus Hunter Profile Set
3117070=Monster Hunter Wilds - BGM: Proof of a Hero (2025 Recording)
3117090=Monster Hunter Wilds - Hunter Layered Armor Set: Feudal Soldier
3117100=Monster Hunter Wilds - Hunter Layered Armor: Fencer's Eyepatch
3117110=Monster Hunter Wilds - Hunter Layered Armor: Oni Horns Wig
3117120=Monster Hunter Wilds - Seikret Decoration: Soldier's Caparison
3117130=Monster Hunter Wilds - Seikret Decoration: General's Caparison
3117140=Monster Hunter Wilds - Felyne Layered Armor Set: Felyne Ashigaru
3117170=Monster Hunter Wilds - Pendant: Avian Wind Chime
3117180=Monster Hunter Wilds - Hairstyle: Hero's Topknot
3117190=Monster Hunter Wilds - Hairstyle: Refined Warrior
3117200=Monster Hunter Wilds - Makeup/Face Paint: Hunter's Kumadori
3117210=Monster Hunter Wilds - Makeup/Face Paint: Special Bloom
3117220=Monster Hunter Wilds - Sticker Set: Avis Unit
3117230=Monster Hunter Wilds - Sticker Set: Monsters of the Windward Plains
3117240=Monster Hunter Wilds - Nameplate: Extra Frame — Russet Dawn
3117250=Monster Hunter Wilds - Hunter Layered Armor Set: Noblesse
3117260=Monster Hunter Wilds - Hunter Layered Armor: Florescent Circlet
3117280=Monster Hunter Wilds - Seikret Decoration: Purehorn Caparison
3117290=Monster Hunter Wilds - Seikret Decoration: Duskhorn Caparison
3117300=Monster Hunter Wilds - Pendant: White Fairy Light
3117310=Monster Hunter Wilds - Pendant: Red Fairy Light
3117320=Monster Hunter Wilds - Pendant: Green Fairy Light
3117330=Monster Hunter Wilds - Pendant: Blue Fairy Light
3117340=Monster Hunter Wilds - Pendant: Violet Fairy Light
3117350=Monster Hunter Wilds - Pendant: Pink Fairy Light
3117370=Monster Hunter Wilds - Photo Pose Set Vol. 1
3117390=Monster Hunter Wilds - Photo Pose: Adventure Begins Pose 1 & 2
3117400=Monster Hunter Wilds - Photo Pose: Adventure Begins Pose 3 & 4
3117430=Monster Hunter Wilds - Makeup/Face Paint: Monoblos Heart
3117440=Monster Hunter Wilds - Tent Customization Set Vol. 1
3117450=Monster Hunter Wilds - Camp Gear Set Vol. 1
3117460=Monster Hunter Wilds - BGM Set Vol. 1
3117500=Monster Hunter Wilds - Sticker Set: Expedition Pals
3117510=Monster Hunter Wilds - Alma Outfit: Scrivener's Coat
3117520=Monster Hunter Wilds - Alma Outfit: New World Commission
3117530=Monster Hunter Wilds - Photo Pose Set Vol. 2
3117540=Monster Hunter Wilds - Gesture: Celebratory Knee Slide
3117550=Monster Hunter Wilds - Gesture: Rearing To Go
3117560=Monster Hunter Wilds - Gesture Set Vol. 2
3157720=Monster Hunter Wilds - Gesture: Battle Cry
3157730=Monster Hunter Wilds - Gesture: Uchiko
3289620=Monster Hunter Wilds - Character Edit Voucher: Three-Voucher Pack
3289630=Monster Hunter Wilds - Character Edit Voucher: Single Voucher (Free Trial Version)
3289640=Monster Hunter Wilds - Alma Outfit: Spring Blossom Kimono
3289650=Monster Hunter Wilds - Seikret Decoration: Majestic Dragon's Caparison
3289660=Monster Hunter Wilds - Pendant: Sakura Posy: White
3289670=Monster Hunter Wilds - Pendant: Sakura Posy: Colorful
3289680=Monster Hunter Wilds - Pendant: White Cat Bell
3289690=Monster Hunter Wilds - Pendant: Black Cat Bell
3289700=Monster Hunter Wilds - Gesture Set Vol. 3
3289710=Monster Hunter Wilds - Sticker Set: Blossomdance
3289720=Monster Hunter Wilds - Hunter Layered Armor Set: Cypurrpunk
3289730=Monster Hunter Wilds - Hairstyle: Wild Braids
3289740=Monster Hunter Wilds - Hairstyle: Futuristic Crop
3289750=Monster Hunter Wilds - Makeup/Face Paint: Drawn Eyelashes
3289760=Monster Hunter Wilds - Makeup/Face Paint: Flames
3289770=Monster Hunter Wilds - Pendant: Strigible: Amstrigian
3289780=Monster Hunter Wilds - Pendant: Strigible: Hymstrigian
3289790=Monster Hunter Wilds - Pendant: Strigible: Cypurrpunk
3308900=Monster Hunter Wilds - High Resolution Texture Pack