[main::general]
# 1=generate newer version of auth ticket, used by some modern apps
# default=0
new_app_ticket=0
# 1=generate/embed Game Coordinator token inside the new auth ticket
# default=0
gc_token=0

[main::connectivity]
# 1=prevent hooking OS networking APIs and allow any external requests
# only used by the experimental builds on **Windows**
# default=0
disable_lan_only=0
# 1=disable all steam networking interface functionality
# this won't prevent games/apps from making external requests
# networking related functionality like lobbies or those that launch a server in the background will not work
# default=0
disable_networking=0
# change the UDP/TCP port the emulator listens on, you should probably not change this because everyone needs to use the same port or you won't find yourselves on the network
# default=47584
listen_port=47584
# 1=pretend steam is running in offline mode, mainly affects the function `ISteamUser::BLoggedOn()`
# Some games that connect to online servers might only work if the steam emu behaves like steam is in offline mode
# default=0
offline=1
# 1=prevent lobby creation in the steam matchmaking interface
# default=0
disable_lobby_creation=0